### ISSUE TITLE
Would it be possible to make this work with the Angular templates?

### ISSUE THREAD

**Issue by Tiberriver256** [elunic/node-ng-lint-staged#2]
I changed the config of lint-staged to be *.html and ran it and got:

```
File 'configurator.component.html' is not part of a TypeScript project 'src/tsconfig.app.json'.
```

The files to get linted just fine when you run `ng lint` manually from the command line though.

**Comment by whefter** [comment]
This is a known limitation, but as far as I can see, it falls in the domain of `ng lint`.

This utility is really only a commandline argument appender. All it does it pass a list of files to the `--files` argument. You can even specify your own additional arguments for `ng lint` (e.g. `--fix` in the example in the README), so if any argument could help with what you're trying to do, it would be here to add it.
