### ISSUE TITLE
ng-lint-staged doesn't work with angular/cli v12

### ISSUE THREAD

**Issue by Charlie91** [elunic/node-ng-lint-staged#4]
```
  "scripts": {
    "lint": "ng lint"
  },
```

```
  "lint-staged": {
    "*.{ts,html}": [
      "ng-lint-staged lint --"
    ]
  }
```

gets me many errors of `Unknown option: '--files'`.

It might be related with the fact that there is no "--files" flag anymore according to docs

https://angular.io/cli/lint

**Comment by tl24** [comment]
You can use --lint-file-patterns instead.

**Comment by whefter** [comment]
Thank you for the hint, I've adjusted the flag and updated the package. The package versions are now a little more aligned with compatible Angular versions.
